import { StyleSheet } from 'react-native';

const layerStyles = StyleSheet.create({
  layerIconBoxPrimary: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.4,
    borderColor: '#6b7280',
    backgroundColor: '#eef2f7',
    transform: [{ translateX: -2 }, { translateY: -2 }],
  },
  layerIconBoxSecondary: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.4,
    borderColor: '#4b5563',
    backgroundColor: '#ffffff',
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  selectorGrid: {
    paddingBottom: 10,
  },
  selectorGroupSection: {
    marginBottom: 8,
  },
  selectorGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 28,
    paddingHorizontal: 0,
    marginBottom: 6,
  },
  selectorGroupCheckAction: {
    width: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  selectorGroupToggleAction: {
    flex: 1,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 2,
    paddingLeft: 2,
  },
  selectorGroupChevronTriangle: {
    width: 0,
    height: 0,
    marginRight: 10,
  },
  selectorGroupChevronCollapsed: {
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderLeftWidth: 7,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#374151',
  },
  selectorGroupChevronExpanded: {
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 7,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#374151',
    marginTop: 1,
  },
  selectorGroupTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
  },
  selectorGroupBody: {
    paddingLeft: 24,
    paddingTop: 0,
  },
  selectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 34,
    marginBottom: 6,
    paddingRight: 6,
  },
  selectorLabel: {
    flex: 1,
    fontSize: 15,
    color: '#2f343a',
    lineHeight: 22,
    fontWeight: '500',
  },
  checkboxOuter: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    marginRight: 10,
    marginTop: 2,
    borderColor: '#b7bcc3',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  checkboxOuterChecked: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  checkboxMark: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 11,
  },
  groupCheckOuter: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#b7bcc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupCheckOuterChecked: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  groupCheckOuterIndeterminate: {
    borderColor: '#2563eb',
    backgroundColor: '#ffffff',
  },
  groupCheckMark: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 11,
  },
  groupCheckIndeterminateMark: {
    width: 8,
    height: 8,
    borderRadius: 1,
    backgroundColor: '#2563eb',
  },
});

export { layerStyles };
