const DIRECTIONS_ACTION_LABEL = 'Chỉ đường';
const DIRECTIONS_LOADING_TEXT = 'Đang tìm đường...';
const DIRECTIONS_EMPTY_TEXT = 'Không tìm được đường đi giữa hai điểm này.';
const DIRECTIONS_PICK_ORIGIN_TEXT = 'Chạm vào bản đồ để chọn điểm bắt đầu';
const DIRECTIONS_PICK_DESTINATION_TEXT = 'Chạm vào bản đồ để chọn điểm đến';
const DIRECTIONS_PICK_ORIGIN_CANCEL = 'Huỷ';
const DIRECTIONS_ORIGIN_LABEL = 'Điểm đi';
const DIRECTIONS_DESTINATION_LABEL = 'Điểm đến';
const DIRECTIONS_MY_LOCATION_TEXT = 'Vị trí của bạn';
const DIRECTIONS_PICKED_POINT_TEXT = 'Điểm bạn đã chọn';
const DIRECTIONS_CHANGE_HINT = 'Chạm để đổi';
const DIRECTIONS_ENDPOINT_ORIGIN = 'origin';
const DIRECTIONS_ENDPOINT_DESTINATION = 'destination';
const DIRECTIONS_STEPS_TITLE = 'Chỉ dẫn từng chặng';
// Route drawing. The renderer takes the /sdk/route payload as-is and decodes
// the polyline natively, so these are only about how it is painted.
const DIRECTIONS_ACTIVE_STROKE_COLOR = '#1D4ED8';
const DIRECTIONS_ACTIVE_STROKE_WIDTH = 6;
const DIRECTIONS_ACTIVE_OUTLINE_COLOR = '#FFFFFF';
const DIRECTIONS_ACTIVE_OUTLINE_WIDTH = 2;
// Labels drawn on the map at each end of the route.
const DIRECTIONS_ORIGIN_POI_COLOR = '#1D4ED8';
const DIRECTIONS_DESTINATION_POI_COLOR = '#B91C1C';

export {
  DIRECTIONS_ACTION_LABEL,
  DIRECTIONS_ACTIVE_OUTLINE_COLOR,
  DIRECTIONS_ACTIVE_OUTLINE_WIDTH,
  DIRECTIONS_ACTIVE_STROKE_COLOR,
  DIRECTIONS_ACTIVE_STROKE_WIDTH,
  DIRECTIONS_CHANGE_HINT,
  DIRECTIONS_DESTINATION_LABEL,
  DIRECTIONS_DESTINATION_POI_COLOR,
  DIRECTIONS_EMPTY_TEXT,
  DIRECTIONS_ENDPOINT_DESTINATION,
  DIRECTIONS_ENDPOINT_ORIGIN,
  DIRECTIONS_LOADING_TEXT,
  DIRECTIONS_MY_LOCATION_TEXT,
  DIRECTIONS_ORIGIN_LABEL,
  DIRECTIONS_ORIGIN_POI_COLOR,
  DIRECTIONS_PICKED_POINT_TEXT,
  DIRECTIONS_PICK_DESTINATION_TEXT,
  DIRECTIONS_PICK_ORIGIN_CANCEL,
  DIRECTIONS_PICK_ORIGIN_TEXT,
  DIRECTIONS_STEPS_TITLE,
};
