import { StyleSheet } from 'react-native';

const searchStyles = StyleSheet.create({
  searchBar: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
    paddingRight: 6,
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    elevation: 5,
  },
  // Magnifier drawn from a bordered circle plus a rotated bar for the handle,
  // so it stays crisp and centred at any size.
  searchIconGlass: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#6b7280',
  },
  searchIconHandle: {
    position: 'absolute',
    right: -1,
    bottom: 0,
    width: 6,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#6b7280',
    transform: [{ rotate: '45deg' }],
  },
  searchIconBox: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#1f2937',
    padding: 0,
  },
  searchClearButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchClearCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchClearBar: {
    position: 'absolute',
    width: 10,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#6b7280',
  },
  searchResults: {
    position: 'absolute',
    top: 66,
    left: 12,
    right: 12,
    maxHeight: 320,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 6,
  },
  searchStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  searchStatusText: {
    marginLeft: 10,
    fontSize: 13,
    color: '#6b7280',
  },
  searchGroupTitle: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  searchRowDivider: {
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  searchRowIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fdf7f7',
    marginRight: 12,
  },
  searchRowIconDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2.5,
    borderColor: '#b91c1c',
  },
  searchRowIconSquare: {
    width: 11,
    height: 11,
    borderRadius: 2,
    borderWidth: 2,
    borderColor: '#0b5df5',
  },
  searchRowIconZone: {
    backgroundColor: '#eff6ff',
  },
  searchRowBody: {
    flex: 1,
  },
  searchRowTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
  },
  searchRowSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: '#9ca3af',
  },
});

export { searchStyles };
