import { StyleSheet } from 'react-native';

// Workaround for a React Native Fabric/Android Yoga bug: an absolutely-positioned
// view stretched via top+bottom (e.g. StyleSheet.absoluteFillObject) can have its
// top offset silently dropped, collapsing the view to zero height pinned at the
// parent's bottom edge. Anchoring with top + height: '100%' instead avoids that
// code path. Do not replace this with absoluteFillObject/bottom-based stretching.
const fullFill = {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  height: '100%',
};

const styles = StyleSheet.create({
  // Every overlay lives inside this one box, which is pinned to the map's
  // measured frame so the two always line up. Before the first measurement it
  // falls back to filling the parent, which is right whenever the parent has no
  // padding of its own.
  mapOverlayRoot: {
    ...fullFill,
  },
  hiddenButton: {
    display: 'none',
  },
  searchContainer: {
    ...fullFill,
  },
  searchBar: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
    paddingRight: 6,
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    elevation: 5,
  },
  // Magnifier drawn from a bordered circle plus a rotated bar for the handle,
  // so it stays crisp and centred at any size.
  searchIconGlass: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#6b7280',
  },
  searchIconHandle: {
    position: 'absolute',
    right: -1,
    bottom: 0,
    width: 6,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#6b7280',
    transform: [{ rotate: '45deg' }],
  },
  searchIconBox: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#1f2937',
    padding: 0,
  },
  searchClearButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchClearCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchClearBar: {
    position: 'absolute',
    width: 10,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#6b7280',
  },
  searchResults: {
    position: 'absolute',
    top: 66,
    left: 12,
    right: 12,
    maxHeight: 320,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 6,
  },
  searchStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  searchStatusText: {
    marginLeft: 10,
    fontSize: 13,
    color: '#6b7280',
  },
  searchGroupTitle: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  searchRowDivider: {
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  searchRowIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fdf7f7',
    marginRight: 12,
  },
  searchRowIconDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2.5,
    borderColor: '#b91c1c',
  },
  searchRowIconSquare: {
    width: 11,
    height: 11,
    borderRadius: 2,
    borderWidth: 2,
    borderColor: '#0b5df5',
  },
  searchRowIconZone: {
    backgroundColor: '#eff6ff',
  },
  searchRowBody: {
    flex: 1,
  },
  searchRowTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
  },
  searchRowSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: '#9ca3af',
  },
  layerButton: {
    position: 'absolute',
    top: 70,
    right: 12,
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 3,
    },
  },
  layerButtonActive: {
    borderColor: '#3b82f6',
    backgroundColor: '#eff6ff',
  },
  legendButton: {
    top: 120,
  },
  layerIconBoxPrimary: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.4,
    borderColor: '#6b7280',
    backgroundColor: '#eef2f7',
    transform: [{ translateX: -2 }, { translateY: -2 }],
  },
  layerIconBoxSecondary: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.4,
    borderColor: '#4b5563',
    backgroundColor: '#ffffff',
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  legendToggleIconRow: {
    width: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 1,
  },
  legendToggleIconDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#4b5563',
    marginRight: 3,
  },
  legendToggleIconLine: {
    flex: 1,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#6b7280',
  },
  selectorContainer: {
    ...fullFill,
  },
  selectorBackdrop: {
    ...fullFill,
    backgroundColor: '#11182740',
  },
  selectorBackdropPressable: {
    ...fullFill,
  },
  selectorPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    width: '76%',
    maxWidth: 320,
    minWidth: 260,
    backgroundColor: '#f3f4f6',
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: {
      width: 2,
      height: 0,
    },
  },
  selectorHeader: {
    marginBottom: 10,
  },
  selectorTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1f2937',
  },
  selectorList: {
    flex: 1,
  },
  selectorGrid: {
    paddingBottom: 10,
  },
  selectorGroupSection: {
    marginBottom: 8,
  },
  selectorGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 28,
    paddingHorizontal: 0,
    marginBottom: 6,
  },
  selectorGroupCheckAction: {
    width: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  selectorGroupToggleAction: {
    flex: 1,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 2,
    paddingLeft: 2,
  },
  selectorGroupChevronTriangle: {
    width: 0,
    height: 0,
    marginRight: 10,
  },
  selectorGroupChevronCollapsed: {
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderLeftWidth: 7,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#374151',
  },
  selectorGroupChevronExpanded: {
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 7,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#374151',
    marginTop: 1,
  },
  selectorGroupTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
  },
  selectorGroupBody: {
    paddingLeft: 24,
    paddingTop: 0,
  },
  selectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 34,
    marginBottom: 6,
    paddingRight: 6,
  },
  selectorLabel: {
    flex: 1,
    fontSize: 15,
    color: '#2f343a',
    lineHeight: 22,
    fontWeight: '500',
  },
  checkboxOuter: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    marginRight: 10,
    marginTop: 2,
    borderColor: '#b7bcc3',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  checkboxOuterChecked: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  checkboxMark: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 11,
  },
  groupCheckOuter: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#b7bcc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupCheckOuterChecked: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  groupCheckOuterIndeterminate: {
    borderColor: '#2563eb',
    backgroundColor: '#ffffff',
  },
  groupCheckMark: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 11,
  },
  groupCheckIndeterminateMark: {
    width: 8,
    height: 8,
    borderRadius: 1,
    backgroundColor: '#2563eb',
  },
  legendList: {
    paddingBottom: 12,
  },
  legendGroup: {
    marginBottom: 14,
  },
  legendGroupTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#b91c1c',
    marginBottom: 8,
  },
  legendItem: {
    marginBottom: 10,
  },
  legendItemTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 6,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 28,
    marginBottom: 4,
    paddingRight: 6,
  },
  // The painted colour of the area, shown only for rules that fill one. The
  // connectivity layers draw pins alone, and their rows leave this out.
  legendSwatch: {
    width: 20,
    height: 13,
    borderRadius: 3,
    marginRight: 8,
  },
  legendIconBox: {
    width: 20,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  legendIconImage: {
    width: 18,
    height: 18,
  },
  legendPin: {
    width: '100%',
    height: '100%',
  },
  // Shows one cell of the sprite sheet over the pin's head: the window is the
  // cell, the sheet behind it is offset so that cell lands inside. Sizes and
  // offsets depend on which cell is drawn, so they are set inline.
  legendSpriteWindow: {
    position: 'absolute',
    overflow: 'hidden',
  },
  legendSpriteSheet: {
    position: 'absolute',
  },
  legendLabel: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: '#374151',
    fontWeight: '500',
  },
  legendDotUnchecked: {
    backgroundColor: '#ffffff',
    borderColor: '#9ca3af',
  },
  sheetContainer: {
    ...fullFill,
  },
  // height is applied at runtime in pixels (see InvestmentSheet), measured from
  // the map area. It is fixed rather than content-driven so the panel geometry
  // never shifts under the snap anchors, which are fractions of the panel's own
  // height: a panel that grew when data replaced the loading state would make
  // the sheet jump. A percentage height is not an option either — it does not
  // resolve reliably against an absolutely positioned parent, letting the panel
  // grow past the top of the map and push its drag header out of view.
  sheetPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: {
      width: 0,
      height: -4,
    },
    elevation: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 56,
    paddingLeft: 16,
    paddingRight: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  sheetHeaderTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
  },
  sheetCloseButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCloseMark: {
    fontSize: 22,
    lineHeight: 24,
    color: '#4b5563',
  },
  // The panel has a fixed height, so the scroll area takes whatever is left
  // between the header and the action bar.
  sheetScroll: {
    flex: 1,
  },
  sheetScrollContent: {
    paddingBottom: 12,
  },
  sheetStatusBox: {
    paddingHorizontal: 16,
    paddingVertical: 28,
    alignItems: 'center',
  },
  sheetStatusText: {
    marginTop: 10,
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  sheetHero: {
    height: 150,
    backgroundColor: '#1f2937',
    justifyContent: 'flex-end',
  },
  sheetHeroImage: {
    ...fullFill,
  },
  sheetHeroScrim: {
    ...fullFill,
    backgroundColor: '#0f172a59',
  },
  sheetHeroContent: {
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  sheetHeroBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: '#ffffff33',
    borderWidth: 1,
    borderColor: '#ffffff80',
    marginBottom: 8,
  },
  sheetHeroBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },
  sheetHeroTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
  },
  sheetHeroSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#e5e7eb',
  },
  sheetSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sheetSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7f1d1d',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  sheetStatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  sheetStatCard: {
    width: '50%',
    paddingHorizontal: 5,
    marginBottom: 10,
  },
  sheetStatCardInner: {
    borderWidth: 1,
    borderColor: '#f1d7d7',
    borderRadius: 10,
    backgroundColor: '#fdf7f7',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sheetStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  sheetStatValue: {
    marginTop: 6,
    fontSize: 18,
    fontWeight: '700',
    color: '#b91c1c',
  },
  sheetOverviewBox: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  sheetOverviewText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#374151',
  },
  sheetChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -3,
  },
  sheetChip: {
    marginHorizontal: 3,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  sheetChipText: {
    fontSize: 12,
    color: '#374151',
    fontWeight: '500',
  },
  sheetCountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  sheetCountLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  sheetCountValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#b91c1c',
  },
  sheetContactBox: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sheetContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 34,
  },
  sheetContactIcon: {
    width: 20,
    fontSize: 13,
    color: '#b91c1c',
  },
  sheetContactText: {
    flex: 1,
    fontSize: 13,
    color: '#374151',
  },
  // Pinned to the bottom of the screen from outside the panel rather than from
  // inside it. It used to live in the panel and be counter-translated into
  // place, which looked right but left its layout position off-screen at the
  // smaller anchors — Android hit-tests against that position, so taps fell
  // straight through to the map. Layout and visual position now agree at every
  // anchor. Elevation must beat the panel's own (12) to paint above it.
  sheetActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    zIndex: 3,
    elevation: 16,
  },
  sheetActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#b91c1c',
  },
  sheetActionButtonGhost: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    marginRight: 8,
  },
  sheetActionLabelGhost: {
    color: '#374151',
  },
  // The wayfinding sign — a diamond with an arrow inside — rather than a bare
  // arrow, which reads as "go" instead of "directions". The two pieces are
  // absolutely positioned siblings, not nested, so the diamond's rotation does
  // not tilt the arrow with it.
  directionsIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  directionsIconDiamond: {
    position: 'absolute',
    left: 3,
    top: 3,
    width: 14,
    height: 14,
    borderWidth: 2,
    borderRadius: 3,
    borderColor: '#374151',
    transform: [{ rotate: '45deg' }],
  },
  directionsIconArrow: {
    position: 'absolute',
    left: 8,
    top: 6.5,
    width: 0,
    height: 0,
    borderTopWidth: 3.5,
    borderBottomWidth: 3.5,
    borderLeftWidth: 5,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#374151',
  },
  // Sits where the search bar would be: the two never show at once.
  pickOriginBanner: {
    position: 'absolute',
    top: 14,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#1f2937',
    paddingLeft: 14,
    paddingRight: 6,
    paddingVertical: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    elevation: 6,
  },
  pickOriginText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: '#ffffff',
    paddingRight: 10,
  },
  pickOriginCancel: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  pickOriginCancelText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fca5a5',
  },
  directionsSummary: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  directionsSummaryRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  directionsDuration: {
    fontSize: 20,
    fontWeight: '700',
    color: '#15803d',
  },
  directionsDistance: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
  },
  directionsSummaryVia: {
    marginTop: 4,
    fontSize: 13,
    color: '#9ca3af',
  },
  directionsEndpoints: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  directionsEndpointRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginHorizontal: -8,
    borderRadius: 10,
  },
  directionsEndpointRowPicking: {
    backgroundColor: '#eff6ff',
  },
  directionsEndpointPlaceholder: {
    color: '#9ca3af',
    fontWeight: '400',
  },
  directionsEndpointHint: {
    marginLeft: 10,
    fontSize: 11,
    fontWeight: '600',
    color: '#2563eb',
  },
  directionsEndpointDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 3,
    borderColor: '#2563eb',
    marginRight: 12,
  },
  directionsEndpointSquare: {
    width: 12,
    height: 12,
    borderRadius: 2,
    borderWidth: 3,
    borderColor: '#b91c1c',
    marginRight: 12,
  },
  directionsEndpointBody: {
    flex: 1,
  },
  directionsEndpointLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  directionsEndpointText: {
    marginTop: 2,
    fontSize: 14,
    color: '#1f2937',
    fontWeight: '500',
  },
  directionsEndpointLine: {
    width: 2,
    height: 14,
    marginLeft: 5,
    backgroundColor: '#e5e7eb',
  },
  directionsStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  directionsStepIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  // Bent turn arrows, each assembled inside this 20x20 box from a stem, the
  // segment it turns into, and a head. Every piece is placed absolutely, so the
  // numbers below are plain coordinates in that box.
  //
  // Head orientation: the corner where the top and right borders meet points
  // north-east, so every rotation is measured from there, clockwise —
  // -45deg aims it up, 0 up-right, 45 right, 90 down-right, 135 down.
  //
  // Left-hand variants reuse these same styles mirrored with scaleX: -1.
  directionsArrow: {
    width: 20,
    height: 20,
  },
  directionsArrowMirrored: {
    transform: [{ scaleX: -1 }],
  },
  arrowStraightStem: {
    position: 'absolute',
    left: 8.9,
    top: 5,
    width: 2.2,
    height: 14,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
  },
  arrowStraightHead: {
    position: 'absolute',
    left: 6.5,
    top: 4.45,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderRightWidth: 2.2,
    borderColor: '#4b5563',
    transform: [{ rotate: '-45deg' }],
  },
  arrowTurnStem: {
    position: 'absolute',
    left: 4.9,
    top: 8,
    width: 2.2,
    height: 11,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
  },
  arrowTurnArm: {
    position: 'absolute',
    left: 4.9,
    top: 8,
    width: 8,
    height: 2.2,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
  },
  arrowTurnHead: {
    position: 'absolute',
    left: 7.55,
    top: 5.6,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderRightWidth: 2.2,
    borderColor: '#4b5563',
    transform: [{ rotate: '45deg' }],
  },
  arrowSlightStem: {
    position: 'absolute',
    left: 4.9,
    top: 11,
    width: 2.2,
    height: 8,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
  },
  arrowSlightArm: {
    position: 'absolute',
    left: 7.73,
    top: 4.17,
    width: 2.2,
    height: 8,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
    transform: [{ rotate: '45deg' }],
  },
  arrowSlightHead: {
    position: 'absolute',
    left: 4.66,
    top: 5.34,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderRightWidth: 2.2,
    borderColor: '#4b5563',
  },
  // The bend sits high and far left so the head, which reaches back 5px from
  // its point, lands clear of the stem instead of on top of it.
  arrowSharpStem: {
    position: 'absolute',
    left: 3.9,
    top: 7,
    width: 2.2,
    height: 12,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
  },
  arrowSharpArm: {
    position: 'absolute',
    left: 6.73,
    top: 5.83,
    width: 2.2,
    height: 8,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
    transform: [{ rotate: '-45deg' }],
  },
  arrowSharpHead: {
    position: 'absolute',
    left: 6.5,
    top: 8.5,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderRightWidth: 2.2,
    borderColor: '#4b5563',
    transform: [{ rotate: '90deg' }],
  },
  arrowUturnDrop: {
    position: 'absolute',
    left: 10.7,
    top: 8,
    width: 2.2,
    height: 5,
    borderRadius: 1.1,
    backgroundColor: '#4b5563',
  },
  arrowUturnHead: {
    position: 'absolute',
    left: 8.3,
    top: 7.55,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderRightWidth: 2.2,
    borderColor: '#4b5563',
    transform: [{ rotate: '135deg' }],
  },
  directionsFinishMark: {
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: '#b91c1c',
  },
  directionsStepBody: {
    flex: 1,
  },
  directionsStepInstruction: {
    fontSize: 14,
    color: '#1f2937',
    lineHeight: 20,
  },
  directionsStepMeta: {
    marginTop: 3,
    fontSize: 12,
    color: '#9ca3af',
  },
  sheetActionIcon: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2.5,
    borderColor: '#ffffff',
    marginRight: 8,
  },
  sheetActionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },
  zoneHeroCode: {
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: '#0f172a80',
  },
  zoneHeroCodeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#e5e7eb',
    letterSpacing: 0.4,
  },
  zoneStatusRow: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  zoneStatusPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
  },
  zoneStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#15803d',
  },
  zoneLabeledBox: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  zoneLabeledBoxLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  zoneLabeledBoxText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#374151',
  },
  zoneParagraphSpacing: {
    marginTop: 8,
  },
  zoneChipDanger: {
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  zoneChipDangerText: {
    color: '#b91c1c',
  },
  zoneStatusPillMuted: {
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  zoneStatusTextMuted: {
    color: '#6b7280',
  },
  zoneInvestorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  zoneInvestorName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    paddingRight: 10,
  },
  zoneInvestorYear: {
    fontSize: 13,
    fontWeight: '600',
    color: '#b91c1c',
  },
  zoneProjectButtonRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 16,
    marginHorizontal: -5,
  },
  zoneProjectButton: {
    flex: 1,
    marginHorizontal: 5,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  zoneProjectButtonPrimary: {
    borderColor: '#7f1d1d',
    backgroundColor: '#7f1d1d',
  },
  zoneProjectButtonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  zoneProjectButtonLabelPrimary: {
    color: '#ffffff',
  },
  sheetBackButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -12,
    marginRight: 2,
  },
  // Drawn from two borders on a rotated square rather than a '‹' glyph: the
  // character sits off-centre in its em box by an amount that differs per
  // platform, so it drifted out of line with the title as it got bigger. A
  // border chevron has no font metrics to fight and stays centred at any size.
  // marginRight offsets the stroke sitting in the left half of the rotated box.
  sheetBackChevron: {
    width: 14,
    height: 14,
    borderLeftWidth: 2.5,
    borderBottomWidth: 2.5,
    borderColor: '#374151',
    transform: [{ rotate: '45deg' }],
    marginRight: 4,
  },
  zoneProjectsHeader: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  zoneProjectsHeaderTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1f2937',
  },
  zoneProjectsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  zoneProjectsHeaderSubtitle: {
    flex: 1,
    fontSize: 13,
    color: '#6b7280',
    paddingRight: 10,
  },
  zoneProjectsCountBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
  },
  zoneProjectsCountText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
  },
  zoneProjectList: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  zoneProjectCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  zoneProjectCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  zoneProjectName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#1f2937',
    paddingRight: 10,
  },
  zoneProjectStatusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  zoneProjectStatusText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#b91c1c',
  },
  zoneProjectCode: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
  },
  zoneProjectSector: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  zoneProjectSectorText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#374151',
  },
  zoneProjectStatRow: {
    flexDirection: 'row',
    marginTop: 12,
    marginHorizontal: -4,
  },
  zoneProjectStatCell: {
    flex: 1,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#f1d7d7',
    borderRadius: 10,
    backgroundColor: '#fdf7f7',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  zoneProjectStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  zoneProjectStatValue: {
    marginTop: 5,
    fontSize: 14,
    fontWeight: '700',
    color: '#b91c1c',
  },
});

export { styles };
