import { StyleSheet } from 'react-native';

// Workaround for a React Native Fabric/Android Yoga bug: an absolutely-positioned
// view stretched via top+bottom (e.g. StyleSheet.absoluteFillObject) can have its
// top offset silently dropped, collapsing the view to zero height pinned at the
// parent's bottom edge. Anchoring with top + height: '100%' instead avoids that
// code path. Do not replace this with absoluteFillObject/bottom-based stretching.
const fullFill = {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  height: '100%',
};

const styles = StyleSheet.create({
  hiddenButton: {
    display: 'none',
  },
  layerButton: {
    position: 'absolute',
    top: 16,
    right: 12,
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 3,
    },
  },
  layerButtonActive: {
    borderColor: '#3b82f6',
    backgroundColor: '#eff6ff',
  },
  legendButton: {
    top: 66,
  },
  layerIconBoxPrimary: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.4,
    borderColor: '#6b7280',
    backgroundColor: '#eef2f7',
    transform: [{ translateX: -2 }, { translateY: -2 }],
  },
  layerIconBoxSecondary: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.4,
    borderColor: '#4b5563',
    backgroundColor: '#ffffff',
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  legendToggleIconRow: {
    width: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 1,
  },
  legendToggleIconDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#4b5563',
    marginRight: 3,
  },
  legendToggleIconLine: {
    flex: 1,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#6b7280',
  },
  selectorContainer: {
    ...fullFill,
  },
  selectorBackdrop: {
    ...fullFill,
    backgroundColor: '#11182740',
  },
  selectorBackdropPressable: {
    ...fullFill,
  },
  selectorPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    width: '76%',
    maxWidth: 320,
    minWidth: 260,
    backgroundColor: '#f3f4f6',
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: {
      width: 2,
      height: 0,
    },
  },
  selectorHeader: {
    marginBottom: 10,
  },
  selectorTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1f2937',
  },
  selectorList: {
    flex: 1,
  },
  selectorGrid: {
    paddingBottom: 10,
  },
  selectorGroupSection: {
    marginBottom: 8,
  },
  selectorGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 28,
    paddingHorizontal: 0,
    marginBottom: 6,
  },
  selectorGroupCheckAction: {
    width: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  selectorGroupToggleAction: {
    flex: 1,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 2,
    paddingLeft: 2,
  },
  selectorGroupChevronTriangle: {
    width: 0,
    height: 0,
    marginRight: 10,
  },
  selectorGroupChevronCollapsed: {
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderLeftWidth: 7,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#374151',
  },
  selectorGroupChevronExpanded: {
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 7,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#374151',
    marginTop: 1,
  },
  selectorGroupTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
  },
  selectorGroupBody: {
    paddingLeft: 24,
    paddingTop: 0,
  },
  selectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 34,
    marginBottom: 6,
    paddingRight: 6,
  },
  selectorLabel: {
    flex: 1,
    fontSize: 15,
    color: '#2f343a',
    lineHeight: 22,
    fontWeight: '500',
  },
  checkboxOuter: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    marginRight: 10,
    marginTop: 2,
    borderColor: '#b7bcc3',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  checkboxOuterChecked: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  checkboxMark: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 11,
  },
  groupCheckOuter: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#b7bcc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupCheckOuterChecked: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  groupCheckOuterIndeterminate: {
    borderColor: '#2563eb',
    backgroundColor: '#ffffff',
  },
  groupCheckMark: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    lineHeight: 11,
  },
  groupCheckIndeterminateMark: {
    width: 8,
    height: 8,
    borderRadius: 1,
    backgroundColor: '#2563eb',
  },
  legendContainer: {
    ...fullFill,
  },
  legendPanel: {
    position: 'absolute',
    right: 12,
    bottom: 20,
    width: 160,
    maxHeight: 240,
    backgroundColor: '#FFFFFFF5',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
  },
  legendTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9ca3af',
    marginBottom: 6,
  },
  legendDivider: {
    height: 1,
    backgroundColor: '#e5e7eb',
    marginBottom: 6,
  },
  legendList: {
    maxHeight: 188,
    marginLeft: -10,
    marginRight: -8,
  },
  legendListInner: {
    paddingBottom: 2,
    paddingHorizontal: 10,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 24,
    marginBottom: 3,
    paddingRight: 2,
  },
  legendLabel: {
    flex: 1,
    fontSize: 13,
    color: '#6b7280',
    fontWeight: '500',
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    marginRight: 8,
    backgroundColor: '#9ca3af',
    borderColor: '#9ca3af',
  },
  legendDotUnchecked: {
    backgroundColor: '#ffffff',
    borderColor: '#9ca3af',
  },
  sheetContainer: {
    ...fullFill,
  },
  // height is applied at runtime in pixels (see InvestmentSheet), measured from
  // the map area. It is fixed rather than content-driven so the panel geometry
  // never shifts under the snap anchors, which are fractions of the panel's own
  // height: a panel that grew when data replaced the loading state would make
  // the sheet jump. A percentage height is not an option either — it does not
  // resolve reliably against an absolutely positioned parent, letting the panel
  // grow past the top of the map and push its drag header out of view.
  sheetPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: {
      width: 0,
      height: -4,
    },
    elevation: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
    paddingLeft: 16,
    paddingRight: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  sheetHeaderTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
  },
  sheetCloseButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCloseMark: {
    fontSize: 20,
    lineHeight: 22,
    color: '#4b5563',
  },
  // The panel has a fixed height, so the scroll area takes whatever is left
  // between the header and the action bar.
  sheetScroll: {
    flex: 1,
  },
  sheetScrollContent: {
    paddingBottom: 12,
  },
  sheetStatusBox: {
    paddingHorizontal: 16,
    paddingVertical: 28,
    alignItems: 'center',
  },
  sheetStatusText: {
    marginTop: 10,
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  sheetHero: {
    height: 150,
    backgroundColor: '#1f2937',
    justifyContent: 'flex-end',
  },
  sheetHeroImage: {
    ...fullFill,
  },
  sheetHeroScrim: {
    ...fullFill,
    backgroundColor: '#0f172a59',
  },
  sheetHeroContent: {
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  sheetHeroBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: '#ffffff33',
    borderWidth: 1,
    borderColor: '#ffffff80',
    marginBottom: 8,
  },
  sheetHeroBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },
  sheetHeroTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
  },
  sheetHeroSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#e5e7eb',
  },
  sheetSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sheetSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7f1d1d',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  sheetStatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  sheetStatCard: {
    width: '50%',
    paddingHorizontal: 5,
    marginBottom: 10,
  },
  sheetStatCardInner: {
    borderWidth: 1,
    borderColor: '#f1d7d7',
    borderRadius: 10,
    backgroundColor: '#fdf7f7',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sheetStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  sheetStatValue: {
    marginTop: 6,
    fontSize: 18,
    fontWeight: '700',
    color: '#b91c1c',
  },
  sheetOverviewBox: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  sheetOverviewText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#374151',
  },
  sheetChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -3,
  },
  sheetChip: {
    marginHorizontal: 3,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  sheetChipText: {
    fontSize: 12,
    color: '#374151',
    fontWeight: '500',
  },
  sheetCountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  sheetCountLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  sheetCountValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#b91c1c',
  },
  sheetContactBox: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sheetContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 34,
  },
  sheetContactIcon: {
    width: 20,
    fontSize: 13,
    color: '#b91c1c',
  },
  sheetContactText: {
    flex: 1,
    fontSize: 13,
    color: '#374151',
  },
  // Counter-translated over the scroll area at the smaller anchors, so it needs
  // to paint above it on both platforms.
  sheetActionBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    zIndex: 2,
    elevation: 4,
  },
  sheetActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#b91c1c',
  },
  sheetActionIcon: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2.5,
    borderColor: '#ffffff',
    marginRight: 8,
  },
  sheetActionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },
  zoneHeroCode: {
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: '#0f172a80',
  },
  zoneHeroCodeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#e5e7eb',
    letterSpacing: 0.4,
  },
  zoneStatusRow: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  zoneStatusPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
  },
  zoneStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#15803d',
  },
  zoneLabeledBox: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  zoneLabeledBoxLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9ca3af',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  zoneLabeledBoxText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#374151',
  },
  zoneParagraphSpacing: {
    marginTop: 8,
  },
  zoneChipDanger: {
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  zoneChipDangerText: {
    color: '#b91c1c',
  },
  zoneStatusPillMuted: {
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  zoneStatusTextMuted: {
    color: '#6b7280',
  },
  zoneInvestorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  zoneInvestorName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    paddingRight: 10,
  },
  zoneInvestorYear: {
    fontSize: 13,
    fontWeight: '600',
    color: '#b91c1c',
  },
  zoneProjectButtonRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 16,
    marginHorizontal: -5,
  },
  zoneProjectButton: {
    flex: 1,
    marginHorizontal: 5,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  zoneProjectButtonPrimary: {
    borderColor: '#7f1d1d',
    backgroundColor: '#7f1d1d',
  },
  zoneProjectButtonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  zoneProjectButtonLabelPrimary: {
    color: '#ffffff',
  },
});

export { styles };
